export const url = 'https://www.apartments.com'
export const keyword = 'Irvine, CA'
export const housingtype = ['Houses', 'Townhomes']
export const minPrice = 1700
export const maxPrice = 6000
export const minBed = 1
export const maxBed = 3
export const lifestyle = 'Senior Housing'
export const bath = '2+'
export const amenities = "Fitness Center, Pool, Elevator, Air Conditioning, Dog Friendly, Cat Friendly"
